# Import

In [1]:
# modules: --------------------------------------------------------------------
import numpy as np
import pandas as pd
from timeit import Timer
from os.path import exists
from collections import defaultdict
from IPython.core.display import display, HTML
import math
from math import floor
import matplotlib.pyplot as plt 
import matplotlib as mpl
import matplotlib.cm as cm
from scipy.stats import norm, t, chi2_contingency, binom, bernoulli, beta, ttest_ind
from function import ci_mean, ci_prop
from warnings import warn
# 79: -------------------------------------------------------------------------

# Question 0: Hierarchical indexing (MultiIndex)
(Reference is [here](https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html)). 

Hierarchical / Multi-level indexing is very exciting as it opens the door to some quite sophisticated data analysis and manipulation, especially for working with higher dimensional data. In essence, it enables you to store and manipulate data with an arbitrary number of dimensions in lower dimensional data structures like Series (1d) and DataFrame (2d).

## Creating a MultiIndex (hierarchical index) object
- The MultiIndex object is the hierarchical analogue of the standard Index object which typically stores the axis labels in pandas objects. You can think of MultiIndex as an array of tuples where each tuple is unique. 
- A MultiIndex can be created from a list of arrays (using MultiIndex.from_arrays()), an array of tuples (using MultiIndex.from_tuples()), a crossed set of iterables (using MultiIndex.from_product()), or a DataFrame (using MultiIndex.from_frame()). 
- The Index constructor will attempt to return a MultiIndex when it is passed a list of tuples.

In [2]:
# Constructing from an array of tuples
arrays = [
    ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
    ["one", "two", "one", "two", "one", "two", "one", "two"],
]
tuples = list(zip(*arrays))
tuples
index = pd.MultiIndex.from_tuples(tuples, names=["first", "second"])
index

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

## Manipulating the dataframe with MultiIndex

- Basic indexing on axis with MultiIndex is illustrated as below.
- The MultiIndex keeps all the defined levels of an index, even if they are not actually used.

In [3]:
# Use the MultiIndex object to construct a dataframe 
df = pd.DataFrame(np.random.randn(3, 8), index=["A", "B", "C"], columns=index)
print(df)
df['bar']

first        bar                 baz                 foo                 qux  \
second       one       two       one       two       one       two       one
A      -1.700524 -0.336100  0.239166 -1.277770  1.076277  0.097609  0.314178
B      -2.237412  1.053934  0.174931  0.706451  1.092140 -0.468536  1.023038
C      -1.266264  0.230887 -1.353216  0.425257 -0.843325  0.573875 -0.792545

first
second       two
A       1.305095
B       0.172536
C       0.632410

second       one       two
A      -1.700524 -0.336100
B      -2.237412  1.053934
C      -1.266264  0.230887

In [4]:
#These two indexing are the same
print(df['bar','one'])
print(df['bar']['one'])

A   -1.700524
B   -2.237412
C   -1.266264
Name: (bar, one), dtype: float64
A   -1.700524
B   -2.237412
C   -1.266264
Name: one, dtype: float64

In [5]:
print(df.columns.levels)  # original MultiIndex
print(df[["foo","qux"]].columns.levels)  # sliced

[['bar', 'baz', 'foo', 'qux'], ['one', 'two']]
[['bar', 'baz', 'foo', 'qux'], ['one', 'two']]

## Advanced indexing with hierarchical index
- MultiIndex keys take the form of tuples. 
- We can use also analogous methods, such as .T, .loc. 
- “Partial” slicing also works quite nicely.

In [6]:
df = df.T
print(df)
print(df.loc[("bar", "two")])
print(df.loc[("bar", "two"), "A"])
print(df.loc["bar"])
print(df.loc["baz":"foo"])

                     A         B         C
first second
bar   one    -1.700524 -2.237412 -1.266264
      two    -0.336100  1.053934  0.230887
baz   one     0.239166  0.174931 -1.353216
      two    -1.277770  0.706451  0.425257
foo   one     1.076277  1.092140 -0.843325
      two     0.097609 -0.468536  0.573875
qux   one     0.314178  1.023038 -0.792545
      two     1.305095  0.172536  0.632410
A   -0.336100
B    1.053934
C    0.230887
Name: (bar, two), dtype: float64
-0.33610031773937954
               A         B         C
second
one    -1.700524 -2.237412 -1.266264
two    -0.336100  1.053934  0.230887
                     A         B         C
first second
baz   one     0.239166  0.174931 -1.353216
      two    -1.277770  0.706451  0.425257
foo   one     1.076277  1.092140 -0.843325
      two     0.097609 -0.468536  0.573875

## Using slicers

- You can slice a MultiIndex by providing multiple indexers.

- You can provide any of the selectors as if you are indexing by label, see Selection by Label, including slices, lists of labels, labels, and boolean indexers.

- You can use slice(None) to select all the contents of that level. You do not need to specify all the deeper levels, they will be implied as slice(None).

- As usual, both sides of the slicers are included as this is label indexing.

In [7]:
def mklbl(prefix, n):
    return ["%s%s" % (prefix, i) for i in range(n)]


miindex = pd.MultiIndex.from_product(
    [mklbl("A", 4), mklbl("B", 2), mklbl("C", 4), mklbl("D", 2)]
)


micolumns = pd.MultiIndex.from_tuples(
    [("a", "foo"), ("a", "bar"), ("b", "foo"), ("b", "bah")], names=["lvl0", "lvl1"]
)


dfmi = (
    pd.DataFrame(
        np.arange(len(miindex) * len(micolumns)).reshape(
            (len(miindex), len(micolumns))
        ),
        index=miindex,
        columns=micolumns,
    )
    .sort_index()
    .sort_index(axis=1)
)

print(dfmi)
print(dfmi.loc[(slice("A1", "A3"), slice(None), ["C1", "C3"]), :])

lvl0           a         b
lvl1         bar  foo  bah  foo
A0 B0 C0 D0    1    0    3    2
         D1    5    4    7    6
      C1 D0    9    8   11   10
         D1   13   12   15   14
      C2 D0   17   16   19   18
...          ...  ...  ...  ...
A3 B1 C1 D1  237  236  239  238
      C2 D0  241  240  243  242
         D1  245  244  247  246
      C3 D0  249  248  251  250
         D1  253  252  255  254

[64 rows x 4 columns]
lvl0           a         b
lvl1         bar  foo  bah  foo
A1 B0 C1 D0   73   72   75   74
         D1   77   76   79   78
      C3 D0   89   88   91   90
         D1   93   92   95   94
   B1 C1 D0  105  104  107  106
         D1  109  108  111  110
      C3 D0  121  120  123  122
         D1  125  124  127  126
A2 B0 C1 D0  137  136  139  138
         D1  141  140  143  142
      C3 D0  153  152  155  154
         D1  157  156  159  158
   B1 C1 D0  169  168  171  170
         D1  173  172  175  174
      C3 D0  185  184  187  186
         D1  189  188  191  190
A3 B0 C1 D0  201  200  203  202
         D1  205  204  207  206
      C3 D0  217  216  219  218
         D1  221  220  223  222
   B1 C1 D0  233  232  235  234
         D1  237  236  239  238
      C3 D0  249  248  251  250
         D1  253  252  255  254

# Question 1

## (a)

In [8]:
# Import data file: ------------------------------------------------------
path = './'
demo_file = path + '/demo.feather'
ohx_file = path + '/ohx.feather'
demo = pd.read_feather(demo_file)
ohx = pd.read_feather(ohx_file)

## (b) 
id (from SEQN)
gender
age
under_20 if age < 20
college - with two levels:
‘some college/college graduate’ or
‘No college/<20’ where the latter category includes everyone under 20 years of age.
exam_status (RIDSTATR)
ohx_status - (OHDDESTS)

In [9]:
# Choose variables needed
demo_less = demo[["id","gender","age","education","exam_status"]]
ohx_less = ohx[["id","dentition_status"]]
# Merge two datasets
data = pd.merge(demo_less,ohx_less,on='id',how='left')
# Create "under_20" variable
data["under_20"] = data["age"]<20
# Create "college" variable
data['college'] = np.where(
    (data['education']=='Some college or AA degree')\
     |(data['education']=='College graduate or above')\
     &(data["age"] >=20),
    'some college/college graduate','No college/<20')
data = data.drop(columns="education")
# Create "ohx" variable
data['ohx'] = np.where(
    (data['exam_status']=='Both interviewed and MEC examined')\
    &(data['dentition_status']=='Complete'),
    'complete','missing'
)
# Rename
data = data.rename(columns = {'dentition_status':'ohx_status'})
data

,id,gender,age,exam_status,ohx_status,under_20,college,ohx
0,62161,Male,22,Both interviewed and MEC examined,Complete,False,No college/<20,complete
1,62162,Female,3,Both interviewed and MEC examined,Complete,True,No college/<20,complete
2,62163,Male,14,Both interviewed and MEC examined,Complete,True,No college/<20,complete
3,62164,Female,44,Both interviewed and MEC examined,Complete,False,some college/college graduate,complete
4,62165,Female,14,Both interviewed and MEC examined,Complete,True,No college/<20,complete
...,...,...,...,...,...,...,...,...
39151,102952,Female,70,Both interviewed and MEC examined,Complete,False,No college/<20,complete
39152,102953,Male,42,Both interviewed and MEC examined,Complete,False,No college/<20,complete
39153,102954,Female,41,Both interviewed and MEC examined,Complete,False,some college/college graduate,complete
39154,102955,Female,14,Both interviewed and MEC examined,Complete,True,No college/<20,complete
39155,102956,Male,38,Both interviewed and MEC examined,Complete,False,some college/college graduate,complete

## (c)
- Number of subjects removed: 1757;
- Number of subjects left: 37399.

In [10]:
data = data[(data['exam_status']=="Both interviewed and MEC examined")]

## (d)

In [34]:
table = pd.DataFrame()
# For categorical varibles
for var in ['gender','under_20','college']:
    # Calculate the size for each of the four groups
    count = data.groupby([var, 'ohx']).size()
    percent = count/data.groupby(var).size()
    df = pd.concat([count,percent],axis=1)
    tab = df.apply(lambda x: 
               '{0:4.0f}({1:.2%})'.format(
                        x[0],
                        x[1]),axis=1)
    # Convert the 1*4 table to 2*2
    tab = tab.reset_index()
    tab = tab.pivot_table(0, var, 'ohx', aggfunc=lambda x: " ".join(x))
    # Convert the 1*4 table to 2*2 for count
    count = pd.DataFrame(count).reset_index()
    count = count.pivot_table(0, var, 'ohx')
    # p value
    _, p, _, _ = chi2_contingency(count)
    tab['p value'] = p
    table = pd.concat([table,tab])
    
# Add continuous variable (i.e., 'age')
age = data.groupby(['ohx']).agg({'age':["mean","std"]})
age = round(age.T,2)
## p value
data_age = data['age']
_, age['p value'] = ttest_ind(data_age[data['ohx']=="complete"],data_age[data['ohx']=="missing"])
table = pd.concat([table,age])


index = [
    np.array(['gender','gender','under_20','under_20','college','college','age','age']),
    np.array(["Female", "Male", "False", "True", "No collge/<20", "some college/college graduate",'mean','std'])
]
table.index = index
table = table.style.format(formatter={'p value': "{:.2e}"})
table.columns.name = 'group'
table

'ohx'

In [30]:
# add a caption: --------------------------------------------------------------
cap = """
<caption style="text-align:justify; caption-side:bottom"> <b> Table 1.</b> 
<em> Summary of the size of different variables with respect to dentition status
</caption>
"""
t1 = table.to_html()
t1 = t1.rsplit('\n')
t1.insert(1, cap)
tab1 = ''
for i, line in enumerate(t1):
    tab1 += line
    if i < (len(t1) - 1):
        tab1 += '\n'
display(HTML(tab1))

# Question 2

## (a)

In [13]:
#Create large dataframe for estimated confidence level
alpha_range = [0.8,0.9,0.95]
method_range = ["Normal","CP","Jeffrey","AC"]
p_range = np.arange(0.05,0.5,0.05)
n_range = range(200,2000,200)
iterables = [alpha_range, method_range,n_range]
index = pd.MultiIndex.from_product(iterables, names=["alpha","method","n"])
conf_level = pd.DataFrame(np.random.randn(len(index), len(p_range)), index=index, columns=p_range)
#Create large dataframe for width of confidence interval
width = pd.DataFrame(np.random.randn(len(index), len(p_range)), index=index, columns=p_range)

In [14]:
for alpha in alpha_range:
    for method in method_range:
        for p in p_range:
            z = norm.ppf(1-(1-alpha)/2)
            n_min = (1/0.005*z*np.sqrt(p*(1-p)))**2 
            for n in n_range:
                level = 0
                wid = 0
                for sim in range(int(n_min)):  
                    x = bernoulli.rvs(p,size = n)
                    res = ci_prop(
                        x,
                        alpha,
                        str_fmt=None,
                        #"{mean:.2f} [{level:.0f}%: ({lwr:.2f}, {upr:.2f})]",
                        method=method
                    )
                    level = level + (res['lwr']<p<res['upr'])
                    wid = wid + res['upr']- res['lwr']
                conf_level.loc[(alpha, method, n),p] = level/n_min
                width.loc[(alpha, method, n),p] = wid/n_min

/Users/shushuz/My Drive/Coursework/STATS507/hw4/function.py:128: Warning: Normal approximation may be incorrect for n * min(p, 1-p) < 12.
  warn(Warning(

KeyboardInterrupt:

In [ ]:
X, Y = np.meshgrid(p_range,n_range)

### Contour Plot for Estimated Confidence Level

In [ ]:
#alpha is 0.8
alpha = 0.8
fig0 = plt.figure()
fig0.suptitle('Estimated Confidence Level with Alpha=0.8')
ax0 = fig0.add_subplot(2, 2, 1)
ax1 = fig0.add_subplot(2, 2, 2)
ax2 = fig0.add_subplot(2, 2, 3) 
ax3 = fig0.add_subplot(2, 2, 4) 
## Normal
CS0 = ax0.contour(X,Y,conf_level.loc[(alpha, "Normal")])
ax0.clabel(CS0, fontsize=10)
ax0.set_title('Normal Approximation')
ax0.set_xlabel('p')
ax0.set_ylabel('n')
## CP
CS1 = ax1.contour(X,Y,conf_level.loc[(alpha, "CP")])
ax1.clabel(CS1, fontsize=10)
ax1.set_title('Clopper-Pearson interval')
ax1.set_xlabel('p')
ax1.set_ylabel('n')
## Jeffrey
CS2 = ax2.contour(X,Y,conf_level.loc[(alpha, "Jeffrey")])
ax2.clabel(CS2, fontsize=10)
ax2.set_title('Jeffrey\'s method')
ax2.set_xlabel('p')
ax2.set_ylabel('n')
## AC
CS3 = ax3.contour(X,Y,conf_level.loc[(alpha, "AC")])
ax3.clabel(CS3, fontsize=10)
ax3.set_title('Agresti-Coull estimates')
ax3.set_xlabel('p')
ax3.set_ylabel('n')

plt.tight_layout()
display()

In [ ]:
#alpha is 0.9
alpha = 0.9
fig0 = plt.figure()
fig0.suptitle('Estimated Confidence Level with Alpha=0.9')
ax0 = fig0.add_subplot(2, 2, 1)
ax1 = fig0.add_subplot(2, 2, 2)
ax2 = fig0.add_subplot(2, 2, 3) 
ax3 = fig0.add_subplot(2, 2, 4) 
## Normal
CS0 = ax0.contour(X,Y,conf_level.loc[(alpha, "Normal")])
ax0.clabel(CS0, fontsize=10)
ax0.set_title('Normal Approximation')
ax0.set_xlabel('p')
ax0.set_ylabel('n')
## CP
CS1 = ax1.contour(X,Y,conf_level.loc[(alpha, "CP")])
ax1.clabel(CS1, fontsize=10)
ax1.set_title('Clopper-Pearson interval')
ax1.set_xlabel('p')
ax1.set_ylabel('n')
## Jeffrey
CS2 = ax2.contour(X,Y,conf_level.loc[(alpha, "Jeffrey")])
ax2.clabel(CS2, fontsize=10)
ax2.set_title('Jeffrey\'s method')
ax2.set_xlabel('p')
ax2.set_ylabel('n')
## AC
CS3 = ax3.contour(X,Y,conf_level.loc[(alpha, "AC")])
ax3.clabel(CS3, fontsize=10)
ax3.set_title('Agresti-Coull estimates')
ax3.set_xlabel('p')
ax3.set_ylabel('n')

plt.tight_layout()
display()

In [ ]:
#alpha is 0.95
alpha = 0.95
fig0 = plt.figure()
fig0.suptitle('Estimated Confidence Width with Alpha=0.95')
ax0 = fig0.add_subplot(2, 2, 1)
ax1 = fig0.add_subplot(2, 2, 2)
ax2 = fig0.add_subplot(2, 2, 3) 
ax3 = fig0.add_subplot(2, 2, 4) 
## Normal
CS0 = ax0.contour(X,Y,conf_level.loc[(alpha, "Normal")])
ax0.clabel(CS0, fontsize=10)
ax0.set_title('Normal Approximation')
ax0.set_xlabel('p')
ax0.set_ylabel('n')
## CP
CS1 = ax1.contour(X,Y,conf_level.loc[(alpha, "CP")])
ax1.clabel(CS1, fontsize=10)
ax1.set_title('Clopper-Pearson interval')
ax1.set_xlabel('p')
ax1.set_ylabel('n')
## Jeffrey
CS2 = ax2.contour(X,Y,conf_level.loc[(alpha, "Jeffrey")])
ax2.clabel(CS2, fontsize=10)
ax2.set_title('Jeffrey\'s method')
ax2.set_xlabel('p')
ax2.set_ylabel('n')
## AC
CS3 = ax3.contour(X,Y,conf_level.loc[(alpha, "AC")])
ax3.clabel(CS3, fontsize=10)
ax3.set_title('Agresti-Coull estimates')
ax3.set_xlabel('p')
ax3.set_ylabel('n')

plt.tight_layout()
display()

## (b)
### Contour plot for Estimated Width of Confidence Interval

In [ ]:
#alpha is 0.8
alpha = 0.8
fig0 = plt.figure()
fig0.suptitle('Estimated Confidence Width with Alpha=0.8')
ax0 = fig0.add_subplot(2, 2, 1)
ax1 = fig0.add_subplot(2, 2, 2)
ax2 = fig0.add_subplot(2, 2, 3) 
ax3 = fig0.add_subplot(2, 2, 4) 
## Normal
CS0 = ax0.contour(X,Y,width.loc[(alpha, "Normal")])
ax0.clabel(CS0, fontsize=10)
ax0.set_title('Normal Approximation')
ax0.set_xlabel('p')
ax0.set_ylabel('n')
## CP
CS1 = ax1.contour(X,Y,width.loc[(alpha, "CP")])
ax1.clabel(CS1, fontsize=10)
ax1.set_title('Clopper-Pearson interval')
ax1.set_xlabel('p')
ax1.set_ylabel('n')
## Jeffrey
CS2 = ax2.contour(X,Y,width.loc[(alpha, "Jeffrey")])
ax2.clabel(CS2, fontsize=10)
ax2.set_title('Jeffrey\'s method')
ax2.set_xlabel('p')
ax2.set_ylabel('n')
## AC
CS3 = ax3.contour(X,Y,width.loc[(alpha, "AC")])
ax3.clabel(CS3, fontsize=10)
ax3.set_title('Agresti-Coull estimates')
ax3.set_xlabel('p')
ax3.set_ylabel('n')

plt.tight_layout()
display()

In [ ]:
#alpha is 0.9
alpha = 0.9
fig0 = plt.figure()
fig0.suptitle('Estimated Confidence Width with Alpha=0.9')
ax0 = fig0.add_subplot(2, 2, 1)
ax1 = fig0.add_subplot(2, 2, 2)
ax2 = fig0.add_subplot(2, 2, 3) 
ax3 = fig0.add_subplot(2, 2, 4) 
## Normal
CS0 = ax0.contour(X,Y,width.loc[(alpha, "Normal")])
ax0.clabel(CS0, fontsize=10)
ax0.set_title('Normal Approximation')
ax0.set_xlabel('p')
ax0.set_ylabel('n')
## CP
CS1 = ax1.contour(X,Y,width.loc[(alpha, "CP")])
ax1.clabel(CS1, fontsize=10)
ax1.set_title('Clopper-Pearson interval')
ax1.set_xlabel('p')
ax1.set_ylabel('n')
## Jeffrey
CS2 = ax2.contour(X,Y,width.loc[(alpha, "Jeffrey")])
ax2.clabel(CS2, fontsize=10)
ax2.set_title('Jeffrey\'s method')
ax2.set_xlabel('p')
ax2.set_ylabel('n')
## AC
CS3 = ax3.contour(X,Y,width.loc[(alpha, "AC")])
ax3.clabel(CS3, fontsize=10)
ax3.set_title('Agresti-Coull estimates')
ax3.set_xlabel('p')
ax3.set_ylabel('n')

plt.tight_layout()
display()

In [ ]:
#alpha is 0.95
alpha = 0.95
fig0 = plt.figure()
fig0.suptitle('Estimated Confidence Width with Alpha=0.95')
ax0 = fig0.add_subplot(2, 2, 1)
ax1 = fig0.add_subplot(2, 2, 2)
ax2 = fig0.add_subplot(2, 2, 3) 
ax3 = fig0.add_subplot(2, 2, 4) 
## Normal
CS0 = ax0.contour(X,Y,width.loc[(alpha, "Normal")])
ax0.clabel(CS0, fontsize=10)
ax0.set_title('Normal Approximation')
ax0.set_xlabel('p')
ax0.set_ylabel('n')
## CP
CS1 = ax1.contour(X,Y,width.loc[(alpha, "CP")])
ax1.clabel(CS1, fontsize=10)
ax1.set_title('Clopper-Pearson interval')
ax1.set_xlabel('p')
ax1.set_ylabel('n')
## Jeffrey
CS2 = ax2.contour(X,Y,width.loc[(alpha, "Jeffrey")])
ax2.clabel(CS2, fontsize=10)
ax2.set_title('Jeffrey\'s method')
ax2.set_xlabel('p')
ax2.set_ylabel('n')
## AC
CS3 = ax3.contour(X,Y,width.loc[(alpha, "AC")])
ax3.clabel(CS3, fontsize=10)
ax3.set_title('Agresti-Coull estimates')
ax3.set_xlabel('p')
ax3.set_ylabel('n')

plt.tight_layout()
display()

### Contour plot for Estimated Relative Width of Confidence Interval

In [ ]:
#relative width
#alpha is 0.8
alpha = 0.8
fig0 = plt.figure()
fig0.suptitle('Relative Confidence Width for different methods with respect to \
Clopper-Pearson interval with Alpha=0.8')
ax0 = fig0.add_subplot(2, 2, 1)
ax2 = fig0.add_subplot(2, 2, 2) 
ax3 = fig0.add_subplot(2, 2, 3) 
## Normal
CS0 = ax0.contour(X,Y,width.loc[(alpha, "Normal")]/width.loc[(alpha, "CP")])
ax0.clabel(CS0, fontsize=10)
ax0.set_title('Normal Approximation')
ax0.set_xlabel('p')
ax0.set_ylabel('n')
## Jeffrey
CS2 = ax2.contour(X,Y,width.loc[(alpha, "Jeffrey")]/width.loc[(alpha, "CP")])
ax2.clabel(CS2, fontsize=10)
ax2.set_title('Jeffrey\'s method')
ax2.set_xlabel('p')
ax2.set_ylabel('n')
## AC
CS3 = ax3.contour(X,Y,width.loc[(alpha, "AC")]/width.loc[(alpha, "CP")])
ax3.clabel(CS3, fontsize=10)
ax3.set_title('Agresti-Coull estimates')
ax3.set_xlabel('p')
ax3.set_ylabel('n')

plt.tight_layout()
display()

In [ ]:
#relative width
#alpha is 0.9
alpha = 0.9
fig0 = plt.figure()
fig0.suptitle('Relative Confidence Width for different methods with respect to \
Clopper-Pearson interval with Alpha=0.9')
ax0 = fig0.add_subplot(2, 2, 1)
ax2 = fig0.add_subplot(2, 2, 2) 
ax3 = fig0.add_subplot(2, 2, 3) 
## Normal
CS0 = ax0.contour(X,Y,width.loc[(alpha, "Normal")]/width.loc[(alpha, "CP")])
ax0.clabel(CS0, fontsize=10)
ax0.set_title('Normal Approximation')
ax0.set_xlabel('p')
ax0.set_ylabel('n')
## Jeffrey
CS2 = ax2.contour(X,Y,width.loc[(alpha, "Jeffrey")]/width.loc[(alpha, "CP")])
ax2.clabel(CS2, fontsize=10)
ax2.set_title('Jeffrey\'s method')
ax2.set_xlabel('p')
ax2.set_ylabel('n')
## AC
CS3 = ax3.contour(X,Y,width.loc[(alpha, "AC")]/width.loc[(alpha, "CP")])
ax3.clabel(CS3, fontsize=10)
ax3.set_title('Agresti-Coull estimates')
ax3.set_xlabel('p')
ax3.set_ylabel('n')

plt.tight_layout()
display()

In [ ]:
#relative width
#alpha is 0.95
alpha = 0.95
fig0 = plt.figure()
fig0.suptitle('Relative Confidence Width for different methods with respect to \
Clopper-Pearson interval with Alpha=0.95')
ax0 = fig0.add_subplot(2, 2, 1)
ax2 = fig0.add_subplot(2, 2, 2) 
ax3 = fig0.add_subplot(2, 2, 3) 
## Normal
CS0 = ax0.contour(X,Y,width.loc[(alpha, "Normal")]/width.loc[(alpha, "CP")])
ax0.clabel(CS0, fontsize=10)
ax0.set_title('Normal Approximation')
ax0.set_xlabel('p')
ax0.set_ylabel('n')
## Jeffrey
CS2 = ax2.contour(X,Y,width.loc[(alpha, "Jeffrey")]/width.loc[(alpha, "CP")])
ax2.clabel(CS2, fontsize=10)
ax2.set_title('Jeffrey\'s method')
ax2.set_xlabel('p')
ax2.set_ylabel('n')
## AC
CS3 = ax3.contour(X,Y,width.loc[(alpha, "AC")]/width.loc[(alpha, "CP")])
ax3.clabel(CS3, fontsize=10)
ax3.set_title('Agresti-Coull estimates')
ax3.set_xlabel('p')
ax3.set_ylabel('n')

plt.tight_layout()
display()