# Imports

In [1]:
# modules: --------------------------------------------------------------------
import numpy as np
import pandas as pd
from timeit import Timer
#from collections import defaultdict
from IPython.core.display import display, HTML
# 79: -------------------------------------------------------------------------

# Question 0: Code Review

## (a) 
For a list of tuples, the code finds (largest) tuples with distinct first elements.

In [2]:
sample_list = [(1, 3, 5), (0, 1, 2), (1, 9, 8)]
op = []
for m in range(len(sample_list)):
    li = [sample_list[m]]
    for n in range(len(sample_list)):
        if (sample_list[m][0] == sample_list[n][0] and
                sample_list[m][-1] != sample_list[n][-1]):
            li.append(sample_list[n])
    op.append(sorted(li, key=lambda dd: dd[-1], reverse=True)[0])
res = list(set(op))
print(res)

[(0, 1, 2), (1, 9, 8)]

## (b) Suggestions
- The indent of the code should be carefully handled. To be more specific, indent four spaces for the code from "for n in range.." to "op.append(...".
- Change the index to the last element instead of a specific one, i.e., change "sample_list\[m\]\[3\] != sample_list\[n\]\[3\]" to "sample_list\[m\]\[-1\] != sample_list\[n\]\[-1\]", and change "dd\[3\]" to "dd\[-1\]". 
- Change variable names to be more literate. For example, change "li" to "pair_list"; change "op" to "represent". 
- The code has O(n^2) time complexity by nested loop, whose computational costs are too high. It can be reduced by going over the entire list only once, i.e. with time complexity O(n). See 2(b) and 2(c) for detailed implementation.

# Question 1

In [3]:
def list_tuple_generator(n, k=3, low=0, high=10):
    output = []
    for i in range(n):
        rng = np.random.default_rng(i)
        output.append(tuple(rng.integers(low=low, high=high, size=k)))
    return (output)

In [4]:
# Test
print(list_tuple_generator(3))
assert isinstance(list_tuple_generator(3), list)
assert isinstance(list_tuple_generator(3)[0], tuple)
assert isinstance(list_tuple_generator(3)[1], tuple)
assert isinstance(list_tuple_generator(3)[2], tuple)

[(8, 6, 5), (4, 5, 7), (8, 2, 1)]

# Question 2

## (a)

In [5]:
def distinct_a(sample_list, key_ele=0, dist_ele=2):
    op = []
    for m in range(len(sample_list)):
        li = [sample_list[m]]
        for n in range(len(sample_list)):
            if (sample_list[m][key_ele] == sample_list[n][key_ele] and
                    sample_list[m][dist_ele] != sample_list[n][dist_ele]):
                li.append(sample_list[n])
        op.append(sorted(li, key=lambda dd: dd[dist_ele], reverse=True)[0])
    res = list(set(op))
    return(res)

In [6]:
sample_list = [(1, 3, 5), (0, 1, 2), (1, 9, 8), (1, 9, 7)]
distinct_a(sample_list)

[(0, 1, 2), (1, 9, 8)]

## (b)

In [7]:
def distinct_b(sample_list, key_ele=0, dist_ele=2):
    res = []
    for m in range(len(sample_list)):
        n = [n for n in range(len(res)) if sample_list[m][key_ele] == res[n][key_ele]]
        if len(n)==0:
            res.append(sample_list[m])
        else:
            res[n[0]] = max(sample_list[m], res[n[0]])
    return(sorted(res))

In [8]:
sample_list = [(1, 3, 5), (0, 1, 2), (1, 9, 8)]
distinct_b(sample_list)

[(0, 1, 2), (1, 9, 8)]

## (c)
I think my code in (b) suffices the requirement of this question. So I just copy and paste my code from (b).

In [9]:
def distinct_c(sample_list, key_ele=0):
    res = dict()
    for m in range(len(sample_list)):
        if sample_list[m][key_ele] in res:
            res[sample_list[m][key_ele]] = max(res[sample_list[m][key_ele]],
                                               sample_list[m])
        else:
            res[sample_list[m][key_ele]] = sample_list[m]
    res = sorted(list(res.values()))
    return(res)

In [10]:
sample_list = [(1, 3, 5), (0, 1, 2), (1, 9, 8)]
distinct_c(sample_list)

[(0, 1, 2), (1, 9, 8)]

## (d)
We can see from the camparison, both (b) and (c) works much better than the original method (a). Generally speaking, (c) performs better than (b). This is because (b) still have to loop over the result list in the process while (c) does not.

In [24]:
size = range(5,100,5)
function = ['a','b','c']
table = pd.DataFrame(columns = function, index = size)
for n in size:
    for fun in function:
        n_mc = 1000 #draw n_mc samples
        time = [] #store computing time for n_mc samples
        for rep in range(n_mc):
            sample = list_tuple_generator(n)
            t = Timer("f(n)", globals={"f": eval("".join(["distinct_",fun])), "n": sample})
            time.append(t.timeit(1))
        table.at[n,fun] = round(np.mean(time) * 1e6, 1)
print(table)

         a      b     c
5      9.9    4.7   2.9
10    21.0    9.8   4.7
15    39.2   16.2   6.7
20    64.2   21.8   8.6
25    92.9   28.7  10.7
30   129.9   36.3  12.6
35   173.3   43.3  14.3
40   221.5   51.3  16.4
45   272.6   59.8  18.9
50   333.0   66.9  20.9
55   404.7   76.7  35.2
60   486.2   84.7  25.1
65   544.4   90.3  26.4
70   630.9   99.6  28.5
75   730.6  107.5  30.6
80   831.1  115.9  33.6
85   954.3  125.6  34.7
90  1074.5  130.8  36.3
95  1190.4  140.4  39.4

# Question 3

## (a)

### Step 1: Read the data and select variables (columns).

In [12]:
url1 = "https://wwwn.cdc.gov/Nchs/Nhanes/2011-2012/DEMO_G.XPT"
url2 = "https://wwwn.cdc.gov/Nchs/Nhanes/2013-2014/DEMO_H.XPT"
url3 = "https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/DEMO_I.XPT"
url4 = "https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/DEMO_J.XPT"
url = [url1,url2,url3,url4]
cohort = ['G','H','I','J']

df = pd.DataFrame()
for i in range(4):
    df_adhoc = pd.read_sas(url[i])
    df_adhoc = df_adhoc[["SEQN", "RIDAGEYR", "RIDRETH3", "DMDEDUC2","DMDMARTL", 
                         "RIDSTATR", "SDMVPSU", "SDMVSTRA", "WTMEC2YR", 
                         "WTINT2YR"]]
    df_adhoc['cohort'] = cohort[i]
    df = pd.concat([df,df_adhoc])
df

,SEQN,RIDAGEYR,RIDRETH3,DMDEDUC2,DMDMARTL,RIDSTATR,SDMVPSU,SDMVSTRA,WTMEC2YR,WTINT2YR,cohort
0,62161.0,22.0,3.0,3.0,5.0,2.0,1.0,91.0,104236.582554,102641.406474,G
1,62162.0,3.0,1.0,NaN,NaN,2.0,3.0,92.0,16116.354010,15457.736897,G
2,62163.0,14.0,6.0,NaN,NaN,2.0,3.0,90.0,7869.485117,7397.684828,G
3,62164.0,44.0,3.0,4.0,1.0,2.0,1.0,94.0,127965.226204,127351.373299,G
4,62165.0,14.0,4.0,NaN,NaN,2.0,2.0,90.0,13384.042162,12209.744980,G
...,...,...,...,...,...,...,...,...,...,...,...
9249,102952.0,70.0,6.0,3.0,1.0,2.0,2.0,138.0,18338.711104,16896.276203,J
9250,102953.0,42.0,1.0,3.0,4.0,2.0,2.0,137.0,63661.951573,61630.380013,J
9251,102954.0,41.0,4.0,5.0,5.0,2.0,1.0,144.0,17694.783346,17160.895269,J
9252,102955.0,14.0,4.0,NaN,NaN,2.0,1.0,136.0,14871.839636,14238.445922,J
9253,102956.0,38.0,3.0,4.0,3.0,2.0,1.0,142.0,39426.299948,38645.740291,J

### Step 2: rename columns

In [13]:
df = df.rename(columns = {"SEQN": "ids", 
                          "RIDAGEYR": "age", 
                          "RIDRETH3": "race/ethnicity", 
                          "DMDEDUC2": "education", 
                          "DMDMARTL": "marital_status"})
df = df.rename(str.lower, axis='columns')
df

,ids,age,race/ethnicity,education,marital_status,ridstatr,sdmvpsu,sdmvstra,wtmec2yr,wtint2yr,cohort
0,62161.0,22.0,3.0,3.0,5.0,2.0,1.0,91.0,104236.582554,102641.406474,G
1,62162.0,3.0,1.0,NaN,NaN,2.0,3.0,92.0,16116.354010,15457.736897,G
2,62163.0,14.0,6.0,NaN,NaN,2.0,3.0,90.0,7869.485117,7397.684828,G
3,62164.0,44.0,3.0,4.0,1.0,2.0,1.0,94.0,127965.226204,127351.373299,G
4,62165.0,14.0,4.0,NaN,NaN,2.0,2.0,90.0,13384.042162,12209.744980,G
...,...,...,...,...,...,...,...,...,...,...,...
9249,102952.0,70.0,6.0,3.0,1.0,2.0,2.0,138.0,18338.711104,16896.276203,J
9250,102953.0,42.0,1.0,3.0,4.0,2.0,2.0,137.0,63661.951573,61630.380013,J
9251,102954.0,41.0,4.0,5.0,5.0,2.0,1.0,144.0,17694.783346,17160.895269,J
9252,102955.0,14.0,4.0,NaN,NaN,2.0,1.0,136.0,14871.839636,14238.445922,J
9253,102956.0,38.0,3.0,4.0,3.0,2.0,1.0,142.0,39426.299948,38645.740291,J

### Step 3: convert to proper types

In [14]:
df = df.convert_dtypes()
#convert 'age' to integer
df['age'] = df['age'].astype(int)
#convert 'ids', 'race/ethnicity', 'education', 'marital_status' into categorical data
for var in ['ids', 'race/ethnicity', 'education', 'marital_status']:
    df[var] = pd.Categorical(df[var])
print(df.dtypes)
print(df.head())

ids               category
age                  int64
race/ethnicity    category
education         category
marital_status    category
ridstatr             Int64
sdmvpsu              Int64
sdmvstra             Int64
wtmec2yr           Float64
wtint2yr           Float64
cohort              string
dtype: object
     ids  age race/ethnicity education marital_status  ridstatr  sdmvpsu  \
0  62161   22              3         3              5         2        1
1  62162    3              1       NaN            NaN         2        3
2  62163   14              6       NaN            NaN         2        3
3  62164   44              3         4              1         2        1
4  62165   14              4       NaN            NaN         2        2

   sdmvstra       wtmec2yr       wtint2yr cohort
0        91  104236.582554  102641.406474      G
1        92    16116.35401   15457.736897      G
2        90    7869.485117    7397.684828      G
3        94  127965.226204  127351.373299      G
4        90   13384.042162    12209.74498      G

### Step 4: export data in pickle format

In [15]:
df.to_pickle('demographic_2011-2018.pkl')

## (b)

In [16]:
url1 = "https://wwwn.cdc.gov/Nchs/Nhanes/2011-2012/OHXDEN_G.XPT"
url2 = "https://wwwn.cdc.gov/Nchs/Nhanes/2013-2014/OHXDEN_H.XPT"
url3 = "https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/OHXDEN_I.XPT"
url4 = "https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/OHXDEN_J.XPT"
url = [url1,url2,url3,url4]
cohort = ['G','H','I','J']

In [18]:
df_oral = pd.DataFrame()
regex_stm = r"OHX.{2}TC|OHX.{2}CTC|SEQN|OHDDESTS"
for i in range(4):
    df_adhoc = pd.read_sas(url[i])
    new_df = df_adhoc.filter(regex=regex_stm, axis=1)
    new_df['cohort'] = cohort[i]
    df_oral = pd.concat([df_oral, new_df])
df_oral

/Users/shushuz/opt/anaconda3/envs/507/lib/python3.9/site-packages/pandas/io/sas/sas_xport.py:475: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  df[x] = v
/var/folders/44/fh7jk3ps13xgzqc8v05brvm40000gs/T/ipykernel_9673/882201406.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['cohort'] = cohort[i]

,SEQN,OHDDESTS,OHX01TC,OHX02TC,OHX03TC,OHX04TC,OHX05TC,OHX06TC,OHX07TC,OHX08TC,...,OHX23CTC,OHX24CTC,OHX25CTC,OHX26CTC,OHX27CTC,OHX28CTC,OHX29CTC,OHX30CTC,OHX31CTC,cohort
0,62161.0,1.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'Z',b'S',G
1,62162.0,1.0,4.0,4.0,4.0,1.0,1.0,1.0,1.0,1.0,...,b'D',b'D',b'D',b'D',b'D',b'D',b'D',b'U',b'U',G
2,62163.0,1.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'Y',b'S',G
3,62164.0,1.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'Z',b'Z',G
4,62165.0,1.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'S',G
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8361,102952.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'S',J
8362,102953.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'Z',J
8363,102954.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,b'S',b'S',b'S',b'S',b'S',b'S',b'F',b'S',b'S',J
8364,102955.0,1.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'Z',J
8365,102956.0,1.0,4.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,...,b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'E',J

In [ ]:
#df = pd.DataFrame()
#regex_stm = r"OHX.{2}TC|OHX.{2}CTC|SEQN|OHDDESTS"
#for test in test1, test2, test3, test4:
#    new_df = test.filter(regex=regex_stm, axis=1)
#    df = pd.concat([df, new_df])
#df

In [19]:
# Rename columns
df_oral = df_oral.rename(columns = {"SEQN": "ids", 
                          "OHDDESTS": "dentition_status"}) 
#                          "OHX.{2}TC": "tooth_count", 
#                          "OHXxxCTC": "coronal_cavities"})
df_oral = df_oral.rename(str.lower, axis='columns')
df_oral

,ids,dentition_status,ohx01tc,ohx02tc,ohx03tc,ohx04tc,ohx05tc,ohx06tc,ohx07tc,ohx08tc,...,ohx23ctc,ohx24ctc,ohx25ctc,ohx26ctc,ohx27ctc,ohx28ctc,ohx29ctc,ohx30ctc,ohx31ctc,cohort
0,62161.0,1.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'Z',b'S',G
1,62162.0,1.0,4.0,4.0,4.0,1.0,1.0,1.0,1.0,1.0,...,b'D',b'D',b'D',b'D',b'D',b'D',b'D',b'U',b'U',G
2,62163.0,1.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'Y',b'S',G
3,62164.0,1.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'Z',b'Z',G
4,62165.0,1.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'S',G
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8361,102952.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'S',J
8362,102953.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'Z',J
8363,102954.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,b'S',b'S',b'S',b'S',b'S',b'S',b'F',b'S',b'S',J
8364,102955.0,1.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'Z',J
8365,102956.0,1.0,4.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,...,b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'E',J

In [20]:
df = df.convert_dtypes()
#convert all variables into categorical data
for var in df.columns:
    df[var] = pd.Categorical(df[var])
df_oral

,ids,dentition_status,ohx01tc,ohx02tc,ohx03tc,ohx04tc,ohx05tc,ohx06tc,ohx07tc,ohx08tc,...,ohx23ctc,ohx24ctc,ohx25ctc,ohx26ctc,ohx27ctc,ohx28ctc,ohx29ctc,ohx30ctc,ohx31ctc,cohort
0,62161.0,1.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'Z',b'S',G
1,62162.0,1.0,4.0,4.0,4.0,1.0,1.0,1.0,1.0,1.0,...,b'D',b'D',b'D',b'D',b'D',b'D',b'D',b'U',b'U',G
2,62163.0,1.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'Y',b'S',G
3,62164.0,1.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'Z',b'Z',G
4,62165.0,1.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'S',G
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8361,102952.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'S',J
8362,102953.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'Z',J
8363,102954.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,b'S',b'S',b'S',b'S',b'S',b'S',b'F',b'S',b'S',J
8364,102955.0,1.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'Z',J
8365,102956.0,1.0,4.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,...,b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'S',b'E',J

In [21]:
df_oral.to_pickle('oral_2011-2018.pkl')

## (c)
- The number of cases in demographic dataset (i.e. (a)) is 39156.
- The number of cases in dentition dataset (i.e. (b)) is 35909.

In [22]:
print(df.shape)
print(df_oral.shape)

(39156, 11)
(35909, 63)